### ISSUE TITLE
SSR support?

### ISSUE THREAD

**Issue by lagleki** [TiE23/metric-teacher#374]
Server-side rendering (good for SEO) doesn't seem to be enabled. Recommendations?

**Comment by TiE23** [comment]
It was something I never had any honest interest in. It seemed like a headache for little gain considering that it appears that Google's crawlers can render JS sites now anyway. Though, looking at my Google site management tools this may not be the case? Anyway, it's not a big worry of mine.

If you want to develop your own fork you're welcome to. This whole project is all in the spirit of education so if you want to fork Metric-Teacher as a base for a Lojban website you're welcome to so long as I get a thank-you credit somewhere. I am not so sure it would make for a good language teaching site, though. You will have to change A LOT, but it'd make me excited to see something like it happen.

Anyway, I'm working at Facebook now so time to work on Metric-Teacher isn't a thing I have a lot of, unfortunately.
